### ISSUE TITLE
Missing WP_CONTENT_URL and and WP_CONTENT_DIR constants

### ISSUE THREAD

**Issue by lstanard** [bokkagroup/catalyst-wp-cli#2]
I believe we will also want to add these lines to the wp-config template:
```
define('WP_CONTENT_DIR', dirname( __FILE__ ) . '/wp-content');
define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/wp-content');
```

Let me know if there's a reason they're not included, otherwise I can add.

**Comment by mikemcguire** [comment]
There is no reason

**Comment by lstanard** [comment]
Updated in 71141f38e5974cc29615b32302fe468c4b9e180e
